//res file generated by ds-servers.com
//visit ds-servers.com
maps/1337_street.res
overviews/1337_street.txt
overviews/1337_street.bmp
sound/ambience/wind1.wav
sound/ambience/wind2.wav
decals.wad
halflife.wad
liquids.wad

gfx/env/citybk.tga
gfx/env/citydn.tga
gfx/env/cityft.tga
gfx/env/citylf.tga
gfx/env/cityrt.tga
gfx/env/cityup.tga