//res file generated by ds-servers.com
//visit ds-servers.com
overviews/2000_2_new.txt
overviews/2000_2_new.bmp
sprites/fire.spr
halflife.wad
liquids.wad
xeno.wad
cached.wad
decals.wad
gfx.wad
pldecal.wad
opfor.wad