//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/ag_bootbox.html
halflife.wad
gfx/env/desertbk.tga
gfx/env/desertdn.tga
gfx/env/desertft.tga
gfx/env/desertlf.tga
gfx/env/desertrt.tga
gfx/env/desertup.tga
maps/ag_bootbox.bsp
maps/ag_bootbox.txt
