//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/ag_crossfirexm.html
sprites/glow02.spr
gfx/env/c2nitebk.tga
gfx/env/c2nitedn.tga
gfx/env/c2niteft.tga
gfx/env/c2nitelf.tga
gfx/env/c2nitert.tga
gfx/env/c2niteup.tga
models/ag_cross/ac_vent.mdl
models/ag_cross/antenna.mdl
models/ag_cross/clock_moving.mdl
models/ag_cross/vend_coke.mdl
models/ag_cross/vend_snack.mdl
models/ag_cross/qk_fan.mdl
models/ag_cross/speaker.mdl
models/ag_cross/couch_black.mdl
sound/ag_s/pib.wav
sound/ag_s/cat06.wav
sound/ag_s/car_alarm.wav
sound/ag_s/ag_cross_kiss_2.wav
sound/ag_s/immigrantsong.wav
maps/ag_crossfirexm.bsp
maps/ag_crossfirexm.txt
