de_storm.wad
fy_marioworld.wad
teylo.wad
maps/ag_crossfire2011.res
gfx/env/polarnight1bk.tga
gfx/env/polarnight1dn.tga
gfx/env/polarnight1ft.tga
gfx/env/polarnight1lf.tga
gfx/env/polarnight1rt.tga
gfx/env/polarnight1up.tga