//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/ag_crossfire4.html
sound/ambience/labdrone2.wav
sound/ambience/labdrone1.wav
sound/ambience/xtal_down1.wav
sound/vox/bloop.wav
sound/ambience/alien_cycletone.wav
sprites/b-tele1.spr
sprites/enter1.spr
sound/ambience/alien_creeper.wav
sound/2017_ag_crossfire/twitchloop.wav
sound/2017_ag_crossfire/lifts.wav
sound/2017_ag_crossfire/ufo1.wav
gfx/env/greenplanets_bk.tga
gfx/env/greenplanets_dn.tga
gfx/env/greenplanets_ft.tga
gfx/env/greenplanets_lf.tga
gfx/env/greenplanets_rt.tga
gfx/env/greenplanets_up.tga
maps/ag_crossfire4.bsp
maps/ag_crossfire4.txt
