cstrike.wad

models/player/cs_arctic/cs_arctic.mdl
models/player/cs_gign/cs_gign.mdl
models/player/cs_gsg9/cs_gsg9.mdl
models/player/cs_guerilla/cs_guerilla.mdl
models/player/cs_leet/cs_leet.mdl
models/player/cs_sas/cs_sas.mdl
models/player/cs_terror/cs_terror.mdl
models/player/cs_urban/cs_urban.mdl
models/player/cs_vip/cs_vip.mdl
models/player/csb_arab/csb_arab.mdl
models/player/cscz_arctic/cscz_arctic.mdl
models/player/cscz_gign/cscz_gign.mdl
models/player/cscz_guerilla/cscz_guerilla.mdl
models/player/cscz_leet/cscz_leet.mdl
models/player/cscz_militia/cscz_militia.mdl
models/player/cscz_sas/cscz_sas.mdl
models/player/cscz_spetsnaz/cscz_spetsnaz.mdl
models/player/cscz_terror/cscz_terror.mdl
models/player/cscz_urban/cscz_urban.mdl
models/player/cscz_vip/cscz_vip.mdl
models/player/css_arctic/css_arctic.mdl
models/player/css_gign/css_gign.mdl
models/player/css_guerilla/css_guerilla.mdl
models/player/css_gsg9/css_gsg9.mdl
models/player/css_leet/css_leet.mdl
models/player/css_sas/css_sas.mdl
models/player/css_terror/css_terror.mdl
models/player/css_urban/css_urban.mdl
models/player/guerilla/guerilla.mdl
models/player/hostage_1/hostage_1.mdl
models/player/hostage_2/hostage_2.mdl

models/player/cs_arctic/cs_arctic.bmp
models/player/cs_gign/cs_gign.bmp
models/player/cs_gsg9/cs_gsg9.bmp
models/player/cs_guerilla/cs_guerilla.bmp
models/player/cs_leet/cs_leet.bmp
models/player/cs_sas/cs_sas.bmp
models/player/cs_terror/cs_terror.bmp
models/player/cs_urban/cs_urban.bmp
models/player/cs_vip/cs_vip.bmp
models/player/csb_arab/csb_arab.bmp
models/player/cscz_arctic/cscz_arctic.bmp
models/player/cscz_gign/cscz_gign.bmp
models/player/cscz_guerilla/cscz_guerilla.bmp
models/player/cscz_leet/cscz_leet.bmp
models/player/cscz_militia/cscz_militia.bmp
models/player/cscz_sas/cscz_sas.bmp
models/player/cscz_spetsnaz/cscz_spetsnaz.bmp
models/player/cscz_terror/cscz_terror.bmp
models/player/cscz_urban/cscz_urban.bmp
models/player/cscz_vip/cscz_vip.bmp
models/player/css_arctic/css_arctic.bmp
models/player/css_gign/css_gign.bmp
models/player/css_guerilla/css_guerilla.bmp
models/player/css_gsg9/css_gsg9.bmp
models/player/css_leet/css_leet.bmp
models/player/css_sas/css_sas.bmp
models/player/css_terror/css_terror.bmp
models/player/css_urban/css_urban.bmp
models/player/guerilla/guerilla.bmp
models/player/hostage_1/hostage_1.bmp
models/player/hostage_2/hostage_2.bmp