models/pred_plant.mdl
sprites/ikgrass1.spr
sprites/ikgrass2.spr
sprites/ikgrass3.spr
sound/ambience/thunder_clap.wav
sound/ambience/rain.wav
gfx/env/doom1up.tga
gfx/env/doom1dn.tga
gfx/env/doom1lf.tga
gfx/env/doom1rt.tga
gfx/env/doom1ft.tga
gfx/env/doom1bk.tga